name: cv
channels:
    - conda-forge
dependencies:
    - grpcio==1.42.0
    - python=3.9
    - pip>=19.0
    - Pillow==9.2.0
    - matplotlib==3.5.3
    - numpy==1.23.2
    - plotly==5.10.0
    - scikit-image==0.19.3
    - scikit-learn==1.1.2
    - scipy==1.9.1
    - tensorboard==2.9.0
    - lime==0.2.0.1
    - pip:
        - tensorflow==2.9.1
        - opencv-contrib-python==4.6.0.66
        - tqdm==4.64.0